### ISSUE TITLE
Create LikeView - Class-based View for handling post likes

### ISSUE THREAD

**Issue by djumanov** [careercraftuz/blog-api#52]
### Overview:

The current project requires the implementation of a new class-based view, **LikeView**, which will handle the functionality related to post likes. The view should support the **POST** method and be accessible at the endpoint **api/like/:id**, where the **:id** parameter represents the post ID.

### URL Parameters:

The **POST** request to the endpoint **api/like/:id** should include the following URL parameters:

| Parameter | Type | Description |
|------|------|------------|
| id | integer | Represents the post's ID |

### Requirements:

The requirements for the **LikeView** are as follows:

1. If the post is being liked for the first time, a reaction should be created with the attribute "like" set to true.
2. If the post is being liked for the second time, the existing reaction should be deleted.
3. If the post is being disliked, the attribute "like" should be set to true.

### Response:

Upon successful execution of the request, the server should respond with a status code of 200 and return the following JSON output:

```json
{
  "id": "id",
  "author_id": "author_id",
  "post_id": "post_id",
  "like": true
}
```

### Note:
Please ensure that the implementation of the **LikeView** adheres to the specified requirements and returns the appropriate response upon successful execution.

**Comment by Snoolf2002** [comment]
How do we send user data? through "body" or through "authorization"?
