### ISSUE TITLE
Create Reaction - Class-based View

### ISSUE THREAD

**Issue by djumanov** [careercraftuz/blog-api#80]
## Create View

View name: **CreateReaction**
methods: **POST**
Auth: TokenAuthentication

Input:
| name | type | required |
|-------|------|----------|
| user | int | yes |
| post | str | yes |
| like | bool | no |

Output:
Status code: 201 (Created)
Response body:

```python
{ "message": "User created successfully." }
```

## Add Url

- `api/create-reaction`

**Comment by geektousif** [comment]
I can do that

**Comment by professorabhay** [comment]
hey @djumanov, I can do this
